version: 2.1

executors:
  qlab:
    working_directory: ~/repository
    docker:
      - image: circleci/node:10.16.3

jobs:
  init:
    executor: qlab
    steps:
      - checkout
      - run:
          name: update yarn
          command: "sudo yarn upgrade"
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  build_test_static:
    executor: qlab
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Run Jest Test
          command: yarn test
      - run:
          name: Testing the Build Process "#Will it Build?"
          command: yarn build

  build_test_functions:
    executor: qlab
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install Dependencies for Hosting
          command: cd functions && npm install && cd ..
      - run:
          name: Run Backend Firebase and Cloud Functions Tests
          command: yarn testFunctions

  deploy_static_dev:
    executor: qlab
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Building the Static Website
          command: yarn build
      - run:
          name: Deploy to Firebase
          command: yarn firebase deploy --token "$FIREBASE_TOKEN" --only hosting -P default

  deploy_functions_dev:
    executor: qlab
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - attach_workspace:
          at: ~/repository/functions
      - run:
          name: Install Dependencies for Hosting
          command: cd functions && npm install && cd ..
      - run:
          name: Deploy Functions
          command: yarn buildFunctions & yarn deployFunctions -P default

  deploy_rules_dev:
    executor: qlab
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Building the Static Website
          command: yarn build
      - run:
          name: Deploy Rules
          command: yarn firebase deploy --token "$FIREBASE_TOKEN" --only firestore:rules -P default

  deploy_prod:
    executor: qlab
    steps:
      - checkout
      - run:
          name: update yarn
          command: "sudo yarn upgrade"
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install Dependencies for Hosting
          command: cd functions && npm install && cd ..
      - run:
          name: SED In New Config
          command: sed -i 's/"DEV"/"PROD"/g' ./src/config/fbConfig.js
      - run:
          name: Rebuild to Prod Version
          command: yarn build
      - run:
          name: Deploy to Production
          command: yarn firebase deploy --token "$FIREBASE_TOKEN" -P production

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - init
      - build_test_static:
          requires:
            - init
      - build_test_functions:
          requires:
            - init
      - deploy_static_dev:
          requires:
            - build_test_static
          filters:
            branches:
              only: master
      - deploy_functions_dev:
          requires:
            - build_test_functions
          filters:
            branches:
              only: master
      - deploy_rules_dev:
          requires:
            - init
          filters:
            branches:
              only: master
      - prod_hold_for_approval:
          type: approval
          requires:
            - deploy_static_dev
            - deploy_functions_dev
            - deploy_rules_dev
      - deploy_prod:
          requires:
            - prod_hold_for_approval
